import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useForm } from "react-hook-form";

type UserMessageType = {
  nome: string;
  email: string;
  mensagem: string;
};

export default function Home() {
  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm<UserMessageType>({});

  const submitForm = (data: UserMessageType) => {
    console.log(data);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Meu Formulario</h1>

        <form onSubmit={handleSubmit(submitForm)}>
          <input
            type="text"
            placeholder="Digite um nome"
            {...(register("nome"), { required: true })}
          />
          <span>
            {errors.nome?.type === "required" && "Nome é obrigatório"}
          </span>
          <br />

          <input
            type="text"
            placeholder="Digite um email"
            {...(register("email"), { required: true })}
          />
          <span>
            {errors.email?.type === "required" && "Nome é obrigatório"}
          </span>
          <br />

          <input
            type="text"
            placeholder="Digite uma mensagem"
            {...(register("mensagem"), { required: true })}
          />
          <span>
            {errors.mensagem?.type === "required" && "Nome é obrigatório"}
          </span>
          <br />

          <input type="submit" />
        </form>
      </main>
    </>
  );
}
