import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { ModalMUI } from "@/components/Modal";
import { Button, Typography } from "@mui/material";
import { useState } from "react";
import DataTable from "@/components/MuiTable";

export default function Home() {
  const [modalOpen, setModalOpen] = useState(false);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Button onClick={() => setModalOpen(true)}> Abrir Modal</Button>
        <ModalMUI open={modalOpen} onClose={() => setModalOpen(false)}>
          <div>
            <DataTable />
          </div>
        </ModalMUI>
      </main>
    </>
  );
}
